-- 001_init.sql — NEUTRALIZED.
--
-- This file originally created a set of PascalCase tables (Company, User,
-- Customer, Product, Sale) that conflicted with the real snake_case schema in
-- 001_initial_schema.sql. The migration runner applies every *.sql file
-- alphabetically and records applied files in the _migrations table, so this
-- file only ever executes once per install.
--
-- Emptying the CREATE statements (rather than deleting the file) is the
-- least-risky fix: fresh installs get only the correct snake_case schema, and
-- existing installs that already recorded this migration are unaffected. The
-- orphan PascalCase tables are no longer created on new installs.
--
-- Intentionally no SQL statements below.
