-- Safely add missing columns if they do not exist
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "drugLicense2" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "drugLicense2" TEXT;
ALTER TABLE "Batch" ADD COLUMN IF NOT EXISTS "freeQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseItem" ADD COLUMN IF NOT EXISTS "freeQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "freeQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseReturnItem" ADD COLUMN IF NOT EXISTS "freeQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SaleReturnItem" ADD COLUMN IF NOT EXISTS "freeQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
