-- AlterTable
ALTER TABLE "Customer" ADD COLUMN "drugLicense2" TEXT;

-- AlterTable
ALTER TABLE "Supplier" ADD COLUMN "drugLicense2" TEXT;

-- AlterTable
ALTER TABLE "Batch" ADD COLUMN "freeQty" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "PurchaseItem" ADD COLUMN "freeQty" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "SaleItem" ADD COLUMN "freeQty" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "PurchaseReturnItem" ADD COLUMN "freeQty" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "SaleReturnItem" ADD COLUMN "freeQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
